### PR TITLE
Upgrade to Go 1.15

### PR DESCRIPTION
**Pull request by jsanda**
Note that #9 should be merged before this.

### CODE REVIEW

**Comment by jsanda** [comment]
@burmanm  now that #9 has been merged can you review this?

**Comment by burmanm** [comment]
I'll try if the docker repo would work now (I couldn't build this)

**Comment by burmanm** [comment]
Now it seems to work, but running ``go mod tidy`` results in a bit cleaner go.sum (by removing some older autorest dependencies)

**Comment by jsanda** [comment]
Here is what I see when I run `go mod tidy`:

```
$ git diff go.mod
diff --git a/go.mod b/go.mod
index 4c814fe..aa94e36 100644
--- a/go.mod
+++ b/go.mod
@@ -18,6 +18,7 @@ require (
 )

 replace (
+       github.com/Azure/go-autorest => github.com/Azure/go-autorest v14.1.0+incompatible
        github.com/datastax/cass-operator => github.com/jsanda/cass-operator v1.0.1-0.20201111154347-91205f4d8f1e
        k8s.io/api => k8s.io/api v0.18.6
        k8s.io/apiextensions-apiserver => k8s.io/apiextensions-apiserver v0.18.6
@@ -40,5 +41,4 @@ replace (
        k8s.io/legacy-cloud-providers => k8s.io/legacy-cloud-providers v0.18.6
        k8s.io/metrics => k8s.io/metrics v0.18.6
        k8s.io/sample-apiserver => k8s.io/sample-apiserver v0.18.6
-       github.com/Azure/go-autorest => github.com/Azure/go-autorest v14.1.0+incompatible
 )
```

@burmanm do you get a different result?

**Comment by burmanm** [comment]
Yeah, it seems larger changes were in the go.sum. Not important.

**Review by burmanm — APPROVED** [review]

**Pull request merged**
